
CREATE TABLE US_Open
(
    id int PRIMARY KEY,
    year int,
    player Char(50),
    finish smallint,
    round_1_score smallint,
    round_2_score smallint,
    round_3_score smallint,
    round_4_score smallint,
    Total_score smallint,
    score_to_par smallint,
    money integer,
    place_after_first smallint,
    place_after_second smallint,
    place_after_third smallint,
    place_after_fourth smallint,
    fairways_hit smallint,
    fairways_rank smallint,
    driving_distance real,
    driving_distance_rank smallint,
    greens_hit smallint,
    greens_hit_rank smallint,
    avg_putts real,
    total_putts smallint,
    putts_rank smallint,
    par_3s smallint,
    par_4s smallint,
    par_5s smallint,
    eagles smallint,
    birdies smallint,
    pars smallint,
    bogeys smallint,
    other smallint
);

CREATE TABLE Masters
(
    id int PRIMARY KEY,
    year int,
    player Char(50),
    finish smallint,
    round_1_score smallint,
    round_2_score smallint,
    round_3_score smallint,
    round_4_score smallint,
    Total_score smallint,
    score_to_par smallint,
    money integer,
    place_after_first smallint,
    place_after_second smallint,
    place_after_third smallint,
    place_after_fourth smallint,
    fairways_hit smallint,
    fairways_rank smallint,
    driving_distance real,
    driving_distance_rank smallint,
    greens_hit smallint,
    greens_hit_rank smallint,
    avg_putts real,
    total_putts smallint,
    putts_rank smallint,
    par_3s smallint,
    par_4s smallint,
    par_5s smallint,
    eagles smallint,
    birdies smallint,
    pars smallint,
    bogeys smallint,
    other smallint
);

CREATE TABLE PGA_Championship
(
    id int PRIMARY KEY,
    year int,
    player Char(50),
    finish smallint,
    round_1_score smallint,
    round_2_score smallint,
    round_3_score smallint,
    round_4_score smallint,
    Total_score smallint,
    score_to_par smallint,
    money integer,
    place_after_first smallint,
    place_after_second smallint,
    place_after_third smallint,
    place_after_fourth smallint,
    fairways_hit smallint,
    fairways_rank smallint,
    driving_distance real,
    driving_distance_rank smallint,
    greens_hit smallint,
    greens_hit_rank smallint,
    avg_putts real,
    total_putts smallint,
    putts_rank smallint,
    par_3s smallint,
    par_4s smallint,
    par_5s smallint,
    eagles smallint,
    birdies smallint,
    pars smallint,
    bogeys smallint,
    other smallint
);

CREATE TABLE Open_Championship
(
    id int PRIMARY KEY,
    year int,
    player Char(50),
    finish smallint,
    round_1_score smallint,
    round_2_score smallint,
    round_3_score smallint,
    round_4_score smallint,
    Total_score smallint,
    score_to_par smallint,
    money integer,
    place_after_first smallint,
    place_after_second smallint,
    place_after_third smallint,
    place_after_fourth smallint,
    fairways_hit smallint,
    fairways_rank smallint,
    driving_distance real,
    driving_distance_rank smallint,
    greens_hit smallint,
    greens_hit_rank smallint,
    avg_putts real,
    total_putts smallint,
    putts_rank smallint,
    par_3s smallint,
    par_4s smallint,
    par_5s smallint,
    eagles smallint,
    birdies smallint,
    pars smallint,
    bogeys smallint,
    other smallint
);

-- \copy
-- pga_test2 from '/Users/dannymorgan/Desktop/Masters_stats/pga_stats.csv' DELIMITER ',' CSV HEADER;